## Driver and Constructor Season Totals for the 2023 season.

In [1]:
import pandas as pd

In [2]:
driver_info = pd.read_csv('f1db_csv/drivers.csv')

In [24]:
constructor_info = pd.read_csv('f1db_csv/constructors.csv')

In [25]:
circuit_info = pd.read_csv('f1db_csv/circuits.csv')

In [4]:
driver_info.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [5]:
constructor_info.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [6]:
driver_standings = pd.read_csv('f1db_csv/driver_standings.csv')

In [7]:
driver_standings.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [8]:
constructor_standings = pd.read_csv('f1db_csv/constructor_standings.csv')

In [9]:
races = pd.read_csv('f1db_csv/races.csv')

In [10]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [15]:
race_data = races.drop(columns=['url', 'time', 'fp1_date', 'fp1_time', "fp2_date", 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_date', 'sprint_time'])

In [21]:
race_data.head()

   raceId  year  round  circuitId                   name        date
0       1  2009      1          1  Australian Grand Prix  2009-03-29
1       2  2009      2          2   Malaysian Grand Prix  2009-04-05
2       3  2009      3         17     Chinese Grand Prix  2009-04-19
3       4  2009      4          3     Bahrain Grand Prix  2009-04-26
4       5  2009      5          4     Spanish Grand Prix  2009-05-10

In [26]:
circuit_info.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

In [40]:
race_data = pd.merge(race_data, circuit_info[['circuitId','location', 'country', 'lat', 'lng']], on='circuitId', how='left')

In [43]:
race_data.head(5)

,raceId,year,round,circuitId,name,date,location,country,lat,lng
0,1,2009,1,1,Australian Grand Prix,2009-03-29,Melbourne,Australia,-37.84970,144.96800
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,Kuala Lumpur,Malaysia,2.76083,101.73800
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,Shanghai,China,31.33890,121.22000
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,Sakhir,Bahrain,26.03250,50.51060
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,Montmeló,Spain,41.57000,2.26111

In [44]:
sprint_data = races[['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'sprint_date']]

In [45]:
sprint_data.head()

,raceId,year,round,circuitId,name,date,sprint_date
0,1,2009,1,1,Australian Grand Prix,2009-03-29,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,\N

In [48]:
sprint_data = sprint_data[sprint_data['sprint_date'] != '\N']

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: malformed \N character escape (3500405112.py, line 1)