### Formula 1 Races

In [70]:
import pandas as pd
import numpy as np

In [71]:
circuits = pd.read_csv('f1db_csv/circuits.csv')

In [72]:
circuits.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

In [73]:
races = pd.read_csv('f1db_csv/races.csv')

In [74]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

##### Clean up race dataframe and remove unnecessary columns
-  We are cleaning up FP practice and qualification data as it isn't necessary for geographical visualization

In [75]:
races = races.drop(['fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_time'], axis=1)

In [76]:
circuit_subset = circuits[['circuitId', 'circuitRef', 'name', 'location', 'country', 'lat', 'lng']]

##### Merge Circuits and Race Data
- Merge on Circuit ID to match circuit information with the race data for each season
- Rename columns for easy readability

In [77]:
races = pd.merge(races, circuit_subset, on='circuitId', how='left')

In [78]:
races.head()

,raceId,year,round,circuitId,name_x,date,time,url,sprint_date,circuitRef,name_y,location,country,lat,lng
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,shanghai,Shanghai International Circuit,Shanghai,China,31.33890,121.22000
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111

In [79]:
races.rename(columns={'raceId':'race_id', 'circuitId':'circuit_id', 'name_y':'circuit_name', 'name_x':'race_name', 'location':'city', 'lng':'lon', 'circuitRef': 'circuit_ref'}, inplace=True)

###### Replace \N values with actual null values

In [81]:
races.replace('\\N', np.nan, inplace=True)

In [82]:
races.head()

,race_id,year,round,circuit_id,race_name,date,time,url,sprint_date,circuit_ref,circuit_name,city,country,lat,lon
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,NaN,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,NaN,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,NaN,shanghai,Shanghai International Circuit,Shanghai,China,31.33890,121.22000
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,NaN,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,NaN,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111

#### Save transformed race/circuit data

In [83]:
races.to_csv('transformed_data/race_data.csv', index=False)